server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /

spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
  aop:
    proxy-target-class: true

mybatis-plus:
  type-aliases-package: com.unshell.easyshiro.*.entity
  # xml 文件扫描
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false
    db-config:
      select-strategy: not_null

app:
  version: 3.1.8
  website: easyshiro.system
  system: easy shiro